### ISSUE TITLE
Doesn't work with image URLs

### ISSUE THREAD

**Issue by renaatdemuynck** [mkdoc/mkabs#1]
Hi, I just found out after some searching and debugging that this tool only works on regular links, but _not_ on image URLs. This could be achieved in a number of ways:
  1. Changing the existing tool to also handle image URLs in the same way
  2. Adding extra options for handling image URLs
  3. Making a separate `mkimg` tool to handle just images.

I personally prefer option two. I was thinking about an option like `imageBase` to allow for different URL's for images (e.g., `https://raw.githubusercontent.com/<vendor>/<package>/master`).

I'm willing to create a pull request for this, but I wanted to wait for some feedback on this …

**Comment by tmpfs** [comment]
Hi @renaatdemuynck,

Thanks for letting me know, I would be happy to review/accept a PR to add this functionality. I agree that option 2) seems like the best approach and happy to use a `imageBase` as an alternative `base` for images when it is specified. If `imageBase` is not given then it should just use `base` I think.

**Comment by renaatdemuynck** [comment]
Okay, I'll have a go at it this afternoon.
Also, to be backwards compatible, I suggest _two_ options:
  - `images` (boolean, default `false`): If `true`, handle images as well (with same base)
  - `imageBase`: (string): the base URL to prepend to image URLs

Two remarks:
  1. I suggest implicitly setting `images` to `true` when `imageBase` is set.
  2. I was thinking about having `imageBase` default to `https://raw.githubusercontent.com/<vendor>/<package>/master`, but that would be biased towards GitHub and would probably be problematic for repos not hosted on GitHub.

**Comment by tmpfs** [comment]
That all sounds good to me except I would prefer not to make assumptions about URLs so please avoid a default for `imageBase` like you mentioned here:

> I was thinking about having imageBase default to https://raw.githubusercontent.com/<vendor>/<package>/master, but that would be biased towards GitHub and would probably be problematic for repos not hosted on GitHub.

**Comment by tmpfs** [comment]
Closing as implemented by #2, thanks 👍

**Comment by tmpfs** [comment]
Bumped a patch version and published it 👍
